# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\wotth\src\someFPS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\wotth\src\someFPS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\wotth\src\someFPS\CMakeFiles C:\Users\wotth\src\someFPS\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\wotth\src\someFPS\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named someFPS

# Build rule for target.
someFPS: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 someFPS
.PHONY : someFPS

# fast build rule for target.
someFPS/fast:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/build
.PHONY : someFPS/fast

Main.obj: Main.cpp.obj

.PHONY : Main.obj

# target to build an object file
Main.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Main.cpp.obj
.PHONY : Main.cpp.obj

Main.i: Main.cpp.i

.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s

.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Main.cpp.s
.PHONY : Main.cpp.s

callbacks/ErrorCallback.obj: callbacks/ErrorCallback.cpp.obj

.PHONY : callbacks/ErrorCallback.obj

# target to build an object file
callbacks/ErrorCallback.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/callbacks/ErrorCallback.cpp.obj
.PHONY : callbacks/ErrorCallback.cpp.obj

callbacks/ErrorCallback.i: callbacks/ErrorCallback.cpp.i

.PHONY : callbacks/ErrorCallback.i

# target to preprocess a source file
callbacks/ErrorCallback.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/callbacks/ErrorCallback.cpp.i
.PHONY : callbacks/ErrorCallback.cpp.i

callbacks/ErrorCallback.s: callbacks/ErrorCallback.cpp.s

.PHONY : callbacks/ErrorCallback.s

# target to generate assembly for a file
callbacks/ErrorCallback.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/callbacks/ErrorCallback.cpp.s
.PHONY : callbacks/ErrorCallback.cpp.s

game/GLFWManager.obj: game/GLFWManager.cpp.obj

.PHONY : game/GLFWManager.obj

# target to build an object file
game/GLFWManager.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/game/GLFWManager.cpp.obj
.PHONY : game/GLFWManager.cpp.obj

game/GLFWManager.i: game/GLFWManager.cpp.i

.PHONY : game/GLFWManager.i

# target to preprocess a source file
game/GLFWManager.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/game/GLFWManager.cpp.i
.PHONY : game/GLFWManager.cpp.i

game/GLFWManager.s: game/GLFWManager.cpp.s

.PHONY : game/GLFWManager.s

# target to generate assembly for a file
game/GLFWManager.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/game/GLFWManager.cpp.s
.PHONY : game/GLFWManager.cpp.s

game/Game.obj: game/Game.cpp.obj

.PHONY : game/Game.obj

# target to build an object file
game/Game.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/game/Game.cpp.obj
.PHONY : game/Game.cpp.obj

game/Game.i: game/Game.cpp.i

.PHONY : game/Game.i

# target to preprocess a source file
game/Game.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/game/Game.cpp.i
.PHONY : game/Game.cpp.i

game/Game.s: game/Game.cpp.s

.PHONY : game/Game.s

# target to generate assembly for a file
game/Game.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/game/Game.cpp.s
.PHONY : game/Game.cpp.s

game/game_objects/GameObject.obj: game/game_objects/GameObject.cpp.obj

.PHONY : game/game_objects/GameObject.obj

# target to build an object file
game/game_objects/GameObject.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/game/game_objects/GameObject.cpp.obj
.PHONY : game/game_objects/GameObject.cpp.obj

game/game_objects/GameObject.i: game/game_objects/GameObject.cpp.i

.PHONY : game/game_objects/GameObject.i

# target to preprocess a source file
game/game_objects/GameObject.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/game/game_objects/GameObject.cpp.i
.PHONY : game/game_objects/GameObject.cpp.i

game/game_objects/GameObject.s: game/game_objects/GameObject.cpp.s

.PHONY : game/game_objects/GameObject.s

# target to generate assembly for a file
game/game_objects/GameObject.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/game/game_objects/GameObject.cpp.s
.PHONY : game/game_objects/GameObject.cpp.s

game/ticking/GameTicker.obj: game/ticking/GameTicker.cpp.obj

.PHONY : game/ticking/GameTicker.obj

# target to build an object file
game/ticking/GameTicker.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/game/ticking/GameTicker.cpp.obj
.PHONY : game/ticking/GameTicker.cpp.obj

game/ticking/GameTicker.i: game/ticking/GameTicker.cpp.i

.PHONY : game/ticking/GameTicker.i

# target to preprocess a source file
game/ticking/GameTicker.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/game/ticking/GameTicker.cpp.i
.PHONY : game/ticking/GameTicker.cpp.i

game/ticking/GameTicker.s: game/ticking/GameTicker.cpp.s

.PHONY : game/ticking/GameTicker.s

# target to generate assembly for a file
game/ticking/GameTicker.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/game/ticking/GameTicker.cpp.s
.PHONY : game/ticking/GameTicker.cpp.s

logger/Logger.obj: logger/Logger.cpp.obj

.PHONY : logger/Logger.obj

# target to build an object file
logger/Logger.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/logger/Logger.cpp.obj
.PHONY : logger/Logger.cpp.obj

logger/Logger.i: logger/Logger.cpp.i

.PHONY : logger/Logger.i

# target to preprocess a source file
logger/Logger.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/logger/Logger.cpp.i
.PHONY : logger/Logger.cpp.i

logger/Logger.s: logger/Logger.cpp.s

.PHONY : logger/Logger.s

# target to generate assembly for a file
logger/Logger.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/logger/Logger.cpp.s
.PHONY : logger/Logger.cpp.s

renderer/Renderer.obj: renderer/Renderer.cpp.obj

.PHONY : renderer/Renderer.obj

# target to build an object file
renderer/Renderer.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/Renderer.cpp.obj
.PHONY : renderer/Renderer.cpp.obj

renderer/Renderer.i: renderer/Renderer.cpp.i

.PHONY : renderer/Renderer.i

# target to preprocess a source file
renderer/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/Renderer.cpp.i
.PHONY : renderer/Renderer.cpp.i

renderer/Renderer.s: renderer/Renderer.cpp.s

.PHONY : renderer/Renderer.s

# target to generate assembly for a file
renderer/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/Renderer.cpp.s
.PHONY : renderer/Renderer.cpp.s

renderer/model/Mesh.obj: renderer/model/Mesh.cpp.obj

.PHONY : renderer/model/Mesh.obj

# target to build an object file
renderer/model/Mesh.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/model/Mesh.cpp.obj
.PHONY : renderer/model/Mesh.cpp.obj

renderer/model/Mesh.i: renderer/model/Mesh.cpp.i

.PHONY : renderer/model/Mesh.i

# target to preprocess a source file
renderer/model/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/model/Mesh.cpp.i
.PHONY : renderer/model/Mesh.cpp.i

renderer/model/Mesh.s: renderer/model/Mesh.cpp.s

.PHONY : renderer/model/Mesh.s

# target to generate assembly for a file
renderer/model/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/model/Mesh.cpp.s
.PHONY : renderer/model/Mesh.cpp.s

renderer/model/Model.obj: renderer/model/Model.cpp.obj

.PHONY : renderer/model/Model.obj

# target to build an object file
renderer/model/Model.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/model/Model.cpp.obj
.PHONY : renderer/model/Model.cpp.obj

renderer/model/Model.i: renderer/model/Model.cpp.i

.PHONY : renderer/model/Model.i

# target to preprocess a source file
renderer/model/Model.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/model/Model.cpp.i
.PHONY : renderer/model/Model.cpp.i

renderer/model/Model.s: renderer/model/Model.cpp.s

.PHONY : renderer/model/Model.s

# target to generate assembly for a file
renderer/model/Model.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/model/Model.cpp.s
.PHONY : renderer/model/Model.cpp.s

renderer/resources/shader/ShaderProgram.obj: renderer/resources/shader/ShaderProgram.cpp.obj

.PHONY : renderer/resources/shader/ShaderProgram.obj

# target to build an object file
renderer/resources/shader/ShaderProgram.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/resources/shader/ShaderProgram.cpp.obj
.PHONY : renderer/resources/shader/ShaderProgram.cpp.obj

renderer/resources/shader/ShaderProgram.i: renderer/resources/shader/ShaderProgram.cpp.i

.PHONY : renderer/resources/shader/ShaderProgram.i

# target to preprocess a source file
renderer/resources/shader/ShaderProgram.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/resources/shader/ShaderProgram.cpp.i
.PHONY : renderer/resources/shader/ShaderProgram.cpp.i

renderer/resources/shader/ShaderProgram.s: renderer/resources/shader/ShaderProgram.cpp.s

.PHONY : renderer/resources/shader/ShaderProgram.s

# target to generate assembly for a file
renderer/resources/shader/ShaderProgram.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/resources/shader/ShaderProgram.cpp.s
.PHONY : renderer/resources/shader/ShaderProgram.cpp.s

renderer/transformation/Transform.obj: renderer/transformation/Transform.cpp.obj

.PHONY : renderer/transformation/Transform.obj

# target to build an object file
renderer/transformation/Transform.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/transformation/Transform.cpp.obj
.PHONY : renderer/transformation/Transform.cpp.obj

renderer/transformation/Transform.i: renderer/transformation/Transform.cpp.i

.PHONY : renderer/transformation/Transform.i

# target to preprocess a source file
renderer/transformation/Transform.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/transformation/Transform.cpp.i
.PHONY : renderer/transformation/Transform.cpp.i

renderer/transformation/Transform.s: renderer/transformation/Transform.cpp.s

.PHONY : renderer/transformation/Transform.s

# target to generate assembly for a file
renderer/transformation/Transform.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/transformation/Transform.cpp.s
.PHONY : renderer/transformation/Transform.cpp.s

renderer/vertex_array/VertexArray.obj: renderer/vertex_array/VertexArray.cpp.obj

.PHONY : renderer/vertex_array/VertexArray.obj

# target to build an object file
renderer/vertex_array/VertexArray.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/vertex_array/VertexArray.cpp.obj
.PHONY : renderer/vertex_array/VertexArray.cpp.obj

renderer/vertex_array/VertexArray.i: renderer/vertex_array/VertexArray.cpp.i

.PHONY : renderer/vertex_array/VertexArray.i

# target to preprocess a source file
renderer/vertex_array/VertexArray.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/vertex_array/VertexArray.cpp.i
.PHONY : renderer/vertex_array/VertexArray.cpp.i

renderer/vertex_array/VertexArray.s: renderer/vertex_array/VertexArray.cpp.s

.PHONY : renderer/vertex_array/VertexArray.s

# target to generate assembly for a file
renderer/vertex_array/VertexArray.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/renderer/vertex_array/VertexArray.cpp.s
.PHONY : renderer/vertex_array/VertexArray.cpp.s

resources/ResourceImpl.obj: resources/ResourceImpl.cpp.obj

.PHONY : resources/ResourceImpl.obj

# target to build an object file
resources/ResourceImpl.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources/ResourceImpl.cpp.obj
.PHONY : resources/ResourceImpl.cpp.obj

resources/ResourceImpl.i: resources/ResourceImpl.cpp.i

.PHONY : resources/ResourceImpl.i

# target to preprocess a source file
resources/ResourceImpl.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources/ResourceImpl.cpp.i
.PHONY : resources/ResourceImpl.cpp.i

resources/ResourceImpl.s: resources/ResourceImpl.cpp.s

.PHONY : resources/ResourceImpl.s

# target to generate assembly for a file
resources/ResourceImpl.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources/ResourceImpl.cpp.s
.PHONY : resources/ResourceImpl.cpp.s

resources/ResourceLoader.obj: resources/ResourceLoader.cpp.obj

.PHONY : resources/ResourceLoader.obj

# target to build an object file
resources/ResourceLoader.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources/ResourceLoader.cpp.obj
.PHONY : resources/ResourceLoader.cpp.obj

resources/ResourceLoader.i: resources/ResourceLoader.cpp.i

.PHONY : resources/ResourceLoader.i

# target to preprocess a source file
resources/ResourceLoader.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources/ResourceLoader.cpp.i
.PHONY : resources/ResourceLoader.cpp.i

resources/ResourceLoader.s: resources/ResourceLoader.cpp.s

.PHONY : resources/ResourceLoader.s

# target to generate assembly for a file
resources/ResourceLoader.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources/ResourceLoader.cpp.s
.PHONY : resources/ResourceLoader.cpp.s

resources/factories/OBJLoader.obj: resources/factories/OBJLoader.cpp.obj

.PHONY : resources/factories/OBJLoader.obj

# target to build an object file
resources/factories/OBJLoader.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources/factories/OBJLoader.cpp.obj
.PHONY : resources/factories/OBJLoader.cpp.obj

resources/factories/OBJLoader.i: resources/factories/OBJLoader.cpp.i

.PHONY : resources/factories/OBJLoader.i

# target to preprocess a source file
resources/factories/OBJLoader.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources/factories/OBJLoader.cpp.i
.PHONY : resources/factories/OBJLoader.cpp.i

resources/factories/OBJLoader.s: resources/factories/OBJLoader.cpp.s

.PHONY : resources/factories/OBJLoader.s

# target to generate assembly for a file
resources/factories/OBJLoader.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources/factories/OBJLoader.cpp.s
.PHONY : resources/factories/OBJLoader.cpp.s

resources/factories/TextLoader.obj: resources/factories/TextLoader.cpp.obj

.PHONY : resources/factories/TextLoader.obj

# target to build an object file
resources/factories/TextLoader.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources/factories/TextLoader.cpp.obj
.PHONY : resources/factories/TextLoader.cpp.obj

resources/factories/TextLoader.i: resources/factories/TextLoader.cpp.i

.PHONY : resources/factories/TextLoader.i

# target to preprocess a source file
resources/factories/TextLoader.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources/factories/TextLoader.cpp.i
.PHONY : resources/factories/TextLoader.cpp.i

resources/factories/TextLoader.s: resources/factories/TextLoader.cpp.s

.PHONY : resources/factories/TextLoader.s

# target to generate assembly for a file
resources/factories/TextLoader.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources/factories/TextLoader.cpp.s
.PHONY : resources/factories/TextLoader.cpp.s

window/Window.obj: window/Window.cpp.obj

.PHONY : window/Window.obj

# target to build an object file
window/Window.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/window/Window.cpp.obj
.PHONY : window/Window.cpp.obj

window/Window.i: window/Window.cpp.i

.PHONY : window/Window.i

# target to preprocess a source file
window/Window.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/window/Window.cpp.i
.PHONY : window/Window.cpp.i

window/Window.s: window/Window.cpp.s

.PHONY : window/Window.s

# target to generate assembly for a file
window/Window.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/window/Window.cpp.s
.PHONY : window/Window.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... someFPS
	@echo ... Main.obj
	@echo ... Main.i
	@echo ... Main.s
	@echo ... callbacks/ErrorCallback.obj
	@echo ... callbacks/ErrorCallback.i
	@echo ... callbacks/ErrorCallback.s
	@echo ... game/GLFWManager.obj
	@echo ... game/GLFWManager.i
	@echo ... game/GLFWManager.s
	@echo ... game/Game.obj
	@echo ... game/Game.i
	@echo ... game/Game.s
	@echo ... game/game_objects/GameObject.obj
	@echo ... game/game_objects/GameObject.i
	@echo ... game/game_objects/GameObject.s
	@echo ... game/ticking/GameTicker.obj
	@echo ... game/ticking/GameTicker.i
	@echo ... game/ticking/GameTicker.s
	@echo ... logger/Logger.obj
	@echo ... logger/Logger.i
	@echo ... logger/Logger.s
	@echo ... renderer/Renderer.obj
	@echo ... renderer/Renderer.i
	@echo ... renderer/Renderer.s
	@echo ... renderer/model/Mesh.obj
	@echo ... renderer/model/Mesh.i
	@echo ... renderer/model/Mesh.s
	@echo ... renderer/model/Model.obj
	@echo ... renderer/model/Model.i
	@echo ... renderer/model/Model.s
	@echo ... renderer/resources/shader/ShaderProgram.obj
	@echo ... renderer/resources/shader/ShaderProgram.i
	@echo ... renderer/resources/shader/ShaderProgram.s
	@echo ... renderer/transformation/Transform.obj
	@echo ... renderer/transformation/Transform.i
	@echo ... renderer/transformation/Transform.s
	@echo ... renderer/vertex_array/VertexArray.obj
	@echo ... renderer/vertex_array/VertexArray.i
	@echo ... renderer/vertex_array/VertexArray.s
	@echo ... resources/ResourceImpl.obj
	@echo ... resources/ResourceImpl.i
	@echo ... resources/ResourceImpl.s
	@echo ... resources/ResourceLoader.obj
	@echo ... resources/ResourceLoader.i
	@echo ... resources/ResourceLoader.s
	@echo ... resources/factories/OBJLoader.obj
	@echo ... resources/factories/OBJLoader.i
	@echo ... resources/factories/OBJLoader.s
	@echo ... resources/factories/TextLoader.obj
	@echo ... resources/factories/TextLoader.i
	@echo ... resources/factories/TextLoader.s
	@echo ... window/Window.obj
	@echo ... window/Window.i
	@echo ... window/Window.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

