# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\wotth\src\someFPS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\wotth\src\someFPS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\wotth\src\someFPS\CMakeFiles C:\Users\wotth\src\someFPS\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\wotth\src\someFPS\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named someFPS

# Build rule for target.
someFPS: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 someFPS
.PHONY : someFPS

# fast build rule for target.
someFPS/fast:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/build
.PHONY : someFPS/fast

ErrorHandler.obj: ErrorHandler.cpp.obj

.PHONY : ErrorHandler.obj

# target to build an object file
ErrorHandler.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/ErrorHandler.cpp.obj
.PHONY : ErrorHandler.cpp.obj

ErrorHandler.i: ErrorHandler.cpp.i

.PHONY : ErrorHandler.i

# target to preprocess a source file
ErrorHandler.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/ErrorHandler.cpp.i
.PHONY : ErrorHandler.cpp.i

ErrorHandler.s: ErrorHandler.cpp.s

.PHONY : ErrorHandler.s

# target to generate assembly for a file
ErrorHandler.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/ErrorHandler.cpp.s
.PHONY : ErrorHandler.cpp.s

IRenderable.obj: IRenderable.cpp.obj

.PHONY : IRenderable.obj

# target to build an object file
IRenderable.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/IRenderable.cpp.obj
.PHONY : IRenderable.cpp.obj

IRenderable.i: IRenderable.cpp.i

.PHONY : IRenderable.i

# target to preprocess a source file
IRenderable.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/IRenderable.cpp.i
.PHONY : IRenderable.cpp.i

IRenderable.s: IRenderable.cpp.s

.PHONY : IRenderable.s

# target to generate assembly for a file
IRenderable.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/IRenderable.cpp.s
.PHONY : IRenderable.cpp.s

Logger.obj: Logger.cpp.obj

.PHONY : Logger.obj

# target to build an object file
Logger.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Logger.cpp.obj
.PHONY : Logger.cpp.obj

Logger.i: Logger.cpp.i

.PHONY : Logger.i

# target to preprocess a source file
Logger.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Logger.cpp.i
.PHONY : Logger.cpp.i

Logger.s: Logger.cpp.s

.PHONY : Logger.s

# target to generate assembly for a file
Logger.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Logger.cpp.s
.PHONY : Logger.cpp.s

Main.obj: Main.cpp.obj

.PHONY : Main.obj

# target to build an object file
Main.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Main.cpp.obj
.PHONY : Main.cpp.obj

Main.i: Main.cpp.i

.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s

.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Main.cpp.s
.PHONY : Main.cpp.s

Renderer.obj: Renderer.cpp.obj

.PHONY : Renderer.obj

# target to build an object file
Renderer.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Renderer.cpp.obj
.PHONY : Renderer.cpp.obj

Renderer.i: Renderer.cpp.i

.PHONY : Renderer.i

# target to preprocess a source file
Renderer.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Renderer.cpp.i
.PHONY : Renderer.cpp.i

Renderer.s: Renderer.cpp.s

.PHONY : Renderer.s

# target to generate assembly for a file
Renderer.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Renderer.cpp.s
.PHONY : Renderer.cpp.s

Shader.obj: Shader.cpp.obj

.PHONY : Shader.obj

# target to build an object file
Shader.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Shader.cpp.obj
.PHONY : Shader.cpp.obj

Shader.i: Shader.cpp.i

.PHONY : Shader.i

# target to preprocess a source file
Shader.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Shader.cpp.i
.PHONY : Shader.cpp.i

Shader.s: Shader.cpp.s

.PHONY : Shader.s

# target to generate assembly for a file
Shader.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Shader.cpp.s
.PHONY : Shader.cpp.s

StateManager.obj: StateManager.cpp.obj

.PHONY : StateManager.obj

# target to build an object file
StateManager.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/StateManager.cpp.obj
.PHONY : StateManager.cpp.obj

StateManager.i: StateManager.cpp.i

.PHONY : StateManager.i

# target to preprocess a source file
StateManager.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/StateManager.cpp.i
.PHONY : StateManager.cpp.i

StateManager.s: StateManager.cpp.s

.PHONY : StateManager.s

# target to generate assembly for a file
StateManager.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/StateManager.cpp.s
.PHONY : StateManager.cpp.s

VertexArray.obj: VertexArray.cpp.obj

.PHONY : VertexArray.obj

# target to build an object file
VertexArray.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/VertexArray.cpp.obj
.PHONY : VertexArray.cpp.obj

VertexArray.i: VertexArray.cpp.i

.PHONY : VertexArray.i

# target to preprocess a source file
VertexArray.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/VertexArray.cpp.i
.PHONY : VertexArray.cpp.i

VertexArray.s: VertexArray.cpp.s

.PHONY : VertexArray.s

# target to generate assembly for a file
VertexArray.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/VertexArray.cpp.s
.PHONY : VertexArray.cpp.s

Window.obj: Window.cpp.obj

.PHONY : Window.obj

# target to build an object file
Window.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Window.cpp.obj
.PHONY : Window.cpp.obj

Window.i: Window.cpp.i

.PHONY : Window.i

# target to preprocess a source file
Window.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Window.cpp.i
.PHONY : Window.cpp.i

Window.s: Window.cpp.s

.PHONY : Window.s

# target to generate assembly for a file
Window.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Window.cpp.s
.PHONY : Window.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... someFPS
	@echo ... ErrorHandler.obj
	@echo ... ErrorHandler.i
	@echo ... ErrorHandler.s
	@echo ... IRenderable.obj
	@echo ... IRenderable.i
	@echo ... IRenderable.s
	@echo ... Logger.obj
	@echo ... Logger.i
	@echo ... Logger.s
	@echo ... Main.obj
	@echo ... Main.i
	@echo ... Main.s
	@echo ... Renderer.obj
	@echo ... Renderer.i
	@echo ... Renderer.s
	@echo ... Shader.obj
	@echo ... Shader.i
	@echo ... Shader.s
	@echo ... StateManager.obj
	@echo ... StateManager.i
	@echo ... StateManager.s
	@echo ... VertexArray.obj
	@echo ... VertexArray.i
	@echo ... VertexArray.s
	@echo ... Window.obj
	@echo ... Window.i
	@echo ... Window.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

