# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\wotth\src\someFPS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\wotth\src\someFPS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\wotth\src\someFPS\CMakeFiles C:\Users\wotth\src\someFPS\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\wotth\src\someFPS\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named someFPS

# Build rule for target.
someFPS: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 someFPS
.PHONY : someFPS

# fast build rule for target.
someFPS/fast:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/build
.PHONY : someFPS/fast

ErrorHandler.obj: ErrorHandler.cpp.obj

.PHONY : ErrorHandler.obj

# target to build an object file
ErrorHandler.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/ErrorHandler.cpp.obj
.PHONY : ErrorHandler.cpp.obj

ErrorHandler.i: ErrorHandler.cpp.i

.PHONY : ErrorHandler.i

# target to preprocess a source file
ErrorHandler.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/ErrorHandler.cpp.i
.PHONY : ErrorHandler.cpp.i

ErrorHandler.s: ErrorHandler.cpp.s

.PHONY : ErrorHandler.s

# target to generate assembly for a file
ErrorHandler.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/ErrorHandler.cpp.s
.PHONY : ErrorHandler.cpp.s

GLFWManager.obj: GLFWManager.cpp.obj

.PHONY : GLFWManager.obj

# target to build an object file
GLFWManager.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/GLFWManager.cpp.obj
.PHONY : GLFWManager.cpp.obj

GLFWManager.i: GLFWManager.cpp.i

.PHONY : GLFWManager.i

# target to preprocess a source file
GLFWManager.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/GLFWManager.cpp.i
.PHONY : GLFWManager.cpp.i

GLFWManager.s: GLFWManager.cpp.s

.PHONY : GLFWManager.s

# target to generate assembly for a file
GLFWManager.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/GLFWManager.cpp.s
.PHONY : GLFWManager.cpp.s

Game.obj: Game.cpp.obj

.PHONY : Game.obj

# target to build an object file
Game.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Game.cpp.obj
.PHONY : Game.cpp.obj

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Game.cpp.s
.PHONY : Game.cpp.s

GameTick.obj: GameTick.cpp.obj

.PHONY : GameTick.obj

# target to build an object file
GameTick.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/GameTick.cpp.obj
.PHONY : GameTick.cpp.obj

GameTick.i: GameTick.cpp.i

.PHONY : GameTick.i

# target to preprocess a source file
GameTick.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/GameTick.cpp.i
.PHONY : GameTick.cpp.i

GameTick.s: GameTick.cpp.s

.PHONY : GameTick.s

# target to generate assembly for a file
GameTick.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/GameTick.cpp.s
.PHONY : GameTick.cpp.s

Logger.obj: Logger.cpp.obj

.PHONY : Logger.obj

# target to build an object file
Logger.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Logger.cpp.obj
.PHONY : Logger.cpp.obj

Logger.i: Logger.cpp.i

.PHONY : Logger.i

# target to preprocess a source file
Logger.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Logger.cpp.i
.PHONY : Logger.cpp.i

Logger.s: Logger.cpp.s

.PHONY : Logger.s

# target to generate assembly for a file
Logger.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Logger.cpp.s
.PHONY : Logger.cpp.s

Main.obj: Main.cpp.obj

.PHONY : Main.obj

# target to build an object file
Main.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Main.cpp.obj
.PHONY : Main.cpp.obj

Main.i: Main.cpp.i

.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s

.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Main.cpp.s
.PHONY : Main.cpp.s

ResourceLoader.obj: ResourceLoader.cpp.obj

.PHONY : ResourceLoader.obj

# target to build an object file
ResourceLoader.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/ResourceLoader.cpp.obj
.PHONY : ResourceLoader.cpp.obj

ResourceLoader.i: ResourceLoader.cpp.i

.PHONY : ResourceLoader.i

# target to preprocess a source file
ResourceLoader.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/ResourceLoader.cpp.i
.PHONY : ResourceLoader.cpp.i

ResourceLoader.s: ResourceLoader.cpp.s

.PHONY : ResourceLoader.s

# target to generate assembly for a file
ResourceLoader.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/ResourceLoader.cpp.s
.PHONY : ResourceLoader.cpp.s

Shader.obj: Shader.cpp.obj

.PHONY : Shader.obj

# target to build an object file
Shader.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Shader.cpp.obj
.PHONY : Shader.cpp.obj

Shader.i: Shader.cpp.i

.PHONY : Shader.i

# target to preprocess a source file
Shader.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Shader.cpp.i
.PHONY : Shader.cpp.i

Shader.s: Shader.cpp.s

.PHONY : Shader.s

# target to generate assembly for a file
Shader.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Shader.cpp.s
.PHONY : Shader.cpp.s

Transform.obj: Transform.cpp.obj

.PHONY : Transform.obj

# target to build an object file
Transform.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Transform.cpp.obj
.PHONY : Transform.cpp.obj

Transform.i: Transform.cpp.i

.PHONY : Transform.i

# target to preprocess a source file
Transform.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Transform.cpp.i
.PHONY : Transform.cpp.i

Transform.s: Transform.cpp.s

.PHONY : Transform.s

# target to generate assembly for a file
Transform.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Transform.cpp.s
.PHONY : Transform.cpp.s

VertexArray.obj: VertexArray.cpp.obj

.PHONY : VertexArray.obj

# target to build an object file
VertexArray.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/VertexArray.cpp.obj
.PHONY : VertexArray.cpp.obj

VertexArray.i: VertexArray.cpp.i

.PHONY : VertexArray.i

# target to preprocess a source file
VertexArray.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/VertexArray.cpp.i
.PHONY : VertexArray.cpp.i

VertexArray.s: VertexArray.cpp.s

.PHONY : VertexArray.s

# target to generate assembly for a file
VertexArray.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/VertexArray.cpp.s
.PHONY : VertexArray.cpp.s

Window.obj: Window.cpp.obj

.PHONY : Window.obj

# target to build an object file
Window.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Window.cpp.obj
.PHONY : Window.cpp.obj

Window.i: Window.cpp.i

.PHONY : Window.i

# target to preprocess a source file
Window.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Window.cpp.i
.PHONY : Window.cpp.i

Window.s: Window.cpp.s

.PHONY : Window.s

# target to generate assembly for a file
Window.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/Window.cpp.s
.PHONY : Window.cpp.s

resources_impl.obj: resources_impl.cpp.obj

.PHONY : resources_impl.obj

# target to build an object file
resources_impl.cpp.obj:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources_impl.cpp.obj
.PHONY : resources_impl.cpp.obj

resources_impl.i: resources_impl.cpp.i

.PHONY : resources_impl.i

# target to preprocess a source file
resources_impl.cpp.i:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources_impl.cpp.i
.PHONY : resources_impl.cpp.i

resources_impl.s: resources_impl.cpp.s

.PHONY : resources_impl.s

# target to generate assembly for a file
resources_impl.cpp.s:
	$(MAKE) -f CMakeFiles\someFPS.dir\build.make CMakeFiles/someFPS.dir/resources_impl.cpp.s
.PHONY : resources_impl.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... someFPS
	@echo ... ErrorHandler.obj
	@echo ... ErrorHandler.i
	@echo ... ErrorHandler.s
	@echo ... GLFWManager.obj
	@echo ... GLFWManager.i
	@echo ... GLFWManager.s
	@echo ... Game.obj
	@echo ... Game.i
	@echo ... Game.s
	@echo ... GameTick.obj
	@echo ... GameTick.i
	@echo ... GameTick.s
	@echo ... Logger.obj
	@echo ... Logger.i
	@echo ... Logger.s
	@echo ... Main.obj
	@echo ... Main.i
	@echo ... Main.s
	@echo ... ResourceLoader.obj
	@echo ... ResourceLoader.i
	@echo ... ResourceLoader.s
	@echo ... Shader.obj
	@echo ... Shader.i
	@echo ... Shader.s
	@echo ... Transform.obj
	@echo ... Transform.i
	@echo ... Transform.s
	@echo ... VertexArray.obj
	@echo ... VertexArray.i
	@echo ... VertexArray.s
	@echo ... Window.obj
	@echo ... Window.i
	@echo ... Window.s
	@echo ... resources_impl.obj
	@echo ... resources_impl.i
	@echo ... resources_impl.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

